spring:
  application:
    name: catalog-service
  data:
    mongodb:
      #uri: mongodb://localhost:27018/catalog
      uri: mongodb://catalog-db:27017/catalog
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    #host: localhost
    port: 5672
  zipkin:
    base-url: http://zipkin:9411
    #base-url: http://localhost:9411
    enabled: true

server:
  port: 8071

queue:
  movie:
    name: MovieQueue
  serie:
    name: SerieQueue

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
      #defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

resilience4j:
  circuitbreaker:
    instances:
      series:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
      movies:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      students:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError
      series:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError