spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: catalog-service-route
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
  zipkin:
    base-url: http://zipkin:9411
    #base-url: http://localhost:9411
    enabled: true

server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
      #defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
