spring:
  application:
    name: serie-service
  data:
    mongodb:
      uri: mongodb://serie-db:27017/series
      #uri: mongodb://localhost:27017/series
  rabbitmq:
    username: guest
    password: guest
    #host: localhost
    host: rabbitmq
    port: 5672
  zipkin:
    #base-url: http://localhost:9411
    base-url: http://zipkin:9411
    enabled: true

server:
  port: 8065

queue:
  serie:
    name: SerieQueue

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
      #defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true